fix(bi-link): isRelativePath invalid in windows
nolebase/integrations pull request #361
Opened 2024-12-01 09:19 UTC by LincZero

2024-12-06 02:00 UTC, nekomeowww commented on packages/markdown-it-bi-directional-links/src/index.ts
> +        if (state.env.relativePath) { // linux
Hmmm. 

This behavior is weird. We should write the comments to tell the later coming developers why these properties, and perhaps we can file up an issue to VitePress to ask them whether this is the unexpected behavior.

2024-12-06 02:00 UTC, nekomeowww commented on packages/markdown-it-bi-directional-links/src/index.ts
> +        if (state.env.relativePath) { // linux
Can we some how write some tests to test these two branches and cobfirm that they are working correctly?

I can help you to configure the test CI to run on both Unix-like OS and Windows.

2024-12-06 09:12 UTC, LincZero commented on packages/markdown-it-bi-directional-links/src/index.ts
> +        if (state.env.relativePath) { // linux
Some notes: https://github.com/nolebase/integrations/pull/344

2024-12-06 09:13 UTC, LincZero commented on packages/markdown-it-bi-directional-links/src/index.ts
> +        if (state.env.relativePath) { // linux
![391230602-807ff1d5-184d-4347-8242-53383e024349-1](https://github.com/user-attachments/assets/82df1a12-7baf-454c-a523-890057ce80c2)

Left: Windows、Right: Linux

2024-12-06 09:32 UTC, LincZero commented on packages/markdown-it-bi-directional-links/src/index.ts
> +        if (state.env.relativePath) { // linux
这个是Markdown-it的state，大概定位了一下：

https://github.com/markdown-it/markdown-it/blob/0fe7ccb4b7f30236fb05f623be6924961d296d3d/lib/rules_core/state_core.mjs#L8

![image](https://github.com/user-attachments/assets/8b7c1a48-3543-4636-beea-9a46b23b068f)

不看代码实现的话没啥头绪，但不想看。我写代码倒没这么严谨。反正这次PR至少不会更糟糕，就不管了。多平台CI倒是可以做

2024-12-06 10:22 UTC, nekomeowww commented
Rebase / Merge is required.

2024-12-18 03:47 UTC, nekomeowww commented
As suggested in https://github.com/nolebase/integrations/pull/361#discussion_r1872462228

> We should write the comments to tell the later coming developers why these properties, and perhaps we can file up an issue to VitePress to ask them whether this is the unexpected behavior.

Or at least, link this PR in the comment.

2024-12-19 05:51 UTC, nekomeowww requested changes

2024-12-19 05:51 UTC, nekomeowww commented on packages/markdown-it-bi-directional-links/src/index.ts
> +        else if (state.env.filePathRelative) { // VuePress, see [#361](nolebase/integrations/pull/361) for details
```suggestion
        else if (state.env.filePathRelative) { // VuePress, see https://github.com/nolebase/integrations/pull/361 for details
```

2024-12-19 05:51 UTC, nekomeowww approved these changes

2024-12-19 10:45 UTC, merged